#
# create django project:
# docker-compose run web django-admin.py startproject composeexample .
# sudo chown -R $USER:$USER .
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',
#         'USER': 'postgres',
#         'HOST': 'db',
#         'PORT': 5432,
#     }
# }
#
version: '2.1'

services:
  web:
    build: .
    command: python c:\\code\\hello.py
    volumes:
      - .:c:\codes
    ports:
      - "900:8000"
      - "1500:5000"
